// internal/auth/password/hasher_test.go
package password

import (
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"testing"

	"golang.org/x/crypto/pbkdf2"
)

func TestArgon2idRoundTrip(t *testing.T) {
	plain := "correct horse battery staple!"
	scheme, hash, err := Hash(plain)
	if err != nil {
		t.Fatalf("hash: %v", err)
	}
	if scheme != SchemeArgon2id {
		t.Fatalf("expected scheme %q, got %q", SchemeArgon2id, scheme)
	}
	if !strings.HasPrefix(hash, "$argon2id$") {
		t.Fatalf("expected argon2id-encoded hash, got %q", hash)
	}
	if err := Verify(scheme, hash, plain); err != nil {
		t.Fatalf("verify accept: %v", err)
	}
	if err := Verify(scheme, hash, "wrong"); !errors.Is(err, ErrPasswordMismatch) {
		t.Fatalf("verify reject: got %v want %v", err, ErrPasswordMismatch)
	}
}

func TestVerifyLegacyPBKDF2(t *testing.T) {
	// Build a known pbkdf2_sha256 hash inline (no Hash() exists for this scheme;
	// we use crypto/pbkdf2 directly), then assert Verify accepts and rejects.
	plain := "legacy-pa55-word-fixture"
	salt := []byte("0123456789abcdef")
	iter := 600000
	key := pbkdf2.Key([]byte(plain), salt, iter, 32, sha256.New)
	encoded := fmt.Sprintf("pbkdf2_sha256$%d$%s$%s",
		iter,
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(key),
	)
	if err := Verify(SchemePBKDF2SHA256, encoded, plain); err != nil {
		t.Fatalf("legacy verify accept: %v", err)
	}
	if err := Verify(SchemePBKDF2SHA256, encoded, "wrong"); !errors.Is(err, ErrPasswordMismatch) {
		t.Fatalf("legacy verify reject: got %v want %v", err, ErrPasswordMismatch)
	}
	// Malformed
	if err := Verify(SchemePBKDF2SHA256, "pbkdf2_sha256$bad", plain); !errors.Is(err, ErrHashCorrupt) {
		t.Fatalf("malformed expected ErrHashCorrupt, got %v", err)
	}
}

func TestVerifyUnknownScheme(t *testing.T) {
	if err := Verify(Scheme("bcrypt-future"), "x", "y"); !errors.Is(err, ErrSchemeUnknown) {
		t.Fatalf("expected ErrSchemeUnknown, got %v", err)
	}
}

// TestVerifyLegacyPBKDF2_URLSafeSalt covers the audit-flagged Bug #1
// (security audit 2026-05-27): Django/Python migrations produce
// pbkdf2_sha256 hashes whose salt is generated by `secrets.token_urlsafe`
// and therefore contains URL-safe base64 characters (`_` or `-`).
// Decoding via RawStdEncoding fails on those characters, so the legacy
// verifier returned ErrHashCorrupt and the user saw "invalid credentials"
// even with the right password.
//
// Production log signal: "password verify failed for collaborator …
// (scheme=pbkdf2_sha256): password hash corrupt".
//
// Fix: try RawURLEncoding when the encoded portions contain URL-safe
// characters, otherwise fall back to RawStdEncoding.
func TestVerifyLegacyPBKDF2_URLSafeSalt(t *testing.T) {
	plain := "django-migration-pa55"
	// Build a salt + key that base64-encodes to characters in the URL
	// alphabet (specifically including `_`). Choosing the byte 0xfb makes
	// the encoder emit '_' in the standard URL-safe alphabet.
	salt := []byte{0xfb, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}
	iter := 210000
	key := pbkdf2.Key([]byte(plain), salt, iter, 32, sha256.New)

	// Encode with URL-safe alphabet (Django default for token_urlsafe).
	encoded := fmt.Sprintf("pbkdf2_sha256$%d$%s$%s",
		iter,
		base64.RawURLEncoding.EncodeToString(salt),
		base64.RawURLEncoding.EncodeToString(key),
	)
	if !strings.ContainsAny(encoded, "_-") {
		t.Fatalf("setup failure: encoded hash %q has no URL-safe chars — test would not exercise the bug", encoded)
	}

	if err := Verify(SchemePBKDF2SHA256, encoded, plain); err != nil {
		t.Fatalf("URL-safe pbkdf2 verify: got %v, want nil (the actual production-affected user case)", err)
	}
	if err := Verify(SchemePBKDF2SHA256, encoded, "wrong"); !errors.Is(err, ErrPasswordMismatch) {
		t.Fatalf("URL-safe pbkdf2 wrong-password: got %v, want ErrPasswordMismatch", err)
	}
}

// TestVerifyLegacyPBKDF2_StandardSaltStillWorks is the regression guard
// for the existing path. Hashes generated with RawStdEncoding must
// continue to verify after the URL-safe fallback is added.
func TestVerifyLegacyPBKDF2_StandardSaltStillWorks(t *testing.T) {
	plain := "standard-base64-pa55"
	// Bytes that encode to characters in the STANDARD alphabet only
	// (`+` and `/` rather than `-` `_`). Byte 0xfb encodes to '+' in
	// the standard alphabet at this position.
	salt := []byte{0xff, 0xfb, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
	iter := 210000
	key := pbkdf2.Key([]byte(plain), salt, iter, 32, sha256.New)

	encoded := fmt.Sprintf("pbkdf2_sha256$%d$%s$%s",
		iter,
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(key),
	)
	if err := Verify(SchemePBKDF2SHA256, encoded, plain); err != nil {
		t.Fatalf("standard pbkdf2 verify regression: got %v, want nil", err)
	}
}

// TestVerifyLegacyPBKDF2_RealDjangoFixture covers the founder-account
// scenario directly: a 12-byte URL-safe salt whose first 8 chars are
// "fxrwhr5_" (the value the audit captured in production logs) — the
// salt actually contains `_`. We pick a deterministic 12-byte salt that
// when base64-url-encoded starts with "fxrwhr5_" so the test mirrors
// reality.
func TestVerifyLegacyPBKDF2_RealDjangoFixture(t *testing.T) {
	plain := "founder-password-fixture"
	// "fxrwhr5_4xyz" — decode URL-safe to get the raw salt bytes.
	rawSalt, err := base64.RawURLEncoding.DecodeString("fxrwhr5_4xyz")
	if err != nil {
		t.Fatalf("setup: decode URL-safe sample salt: %v", err)
	}
	iter := 210000
	key := pbkdf2.Key([]byte(plain), rawSalt, iter, 32, sha256.New)

	encoded := fmt.Sprintf("pbkdf2_sha256$%d$%s$%s",
		iter,
		"fxrwhr5_4xyz",
		base64.RawURLEncoding.EncodeToString(key),
	)
	if err := Verify(SchemePBKDF2SHA256, encoded, plain); err != nil {
		t.Fatalf("Django fixture verify: got %v, want nil (this is the founder login bug)", err)
	}
}
