package model

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// MaterializeProductRequest resolves one stored product and persists a materialized snapshot.
type MaterializeProductRequest struct {
	Product ManifestSelector `json:"product"`
}

// ProductMaterializationComponent traces one component rewritten during materialization.
type ProductMaterializationComponent struct {
	Name                string             `json:"name"`
	SourceKind          string             `json:"source_kind"`
	ResolvedSourceKind  string             `json:"resolved_source_kind"`
	Operation           string             `json:"operation,omitempty"`
	Capability          string             `json:"capability,omitempty"`
	Input               map[string]any     `json:"input,omitempty"`
	IntegrationType     *ManifestReference `json:"integration_type,omitempty"`
	IntegrationInstance *ManifestReference `json:"integration_instance,omitempty"`
	Metadata            map[string]any     `json:"metadata,omitempty"`
}

// ProductMaterialization is the persisted, audit-friendly snapshot of one product resolution.
type ProductMaterialization struct {
	ID                   uuid.UUID                         `json:"id"`
	Product              ManifestReference                 `json:"product"`
	ProductChecksum      string                            `json:"product_checksum"`
	MaterializedChecksum string                            `json:"materialized_checksum"`
	MaterializedSpec     json.RawMessage                   `json:"materialized_spec"`
	Components           []ProductMaterializationComponent `json:"components,omitempty"`
	CreatedAt            time.Time                         `json:"created_at"`
}

// MaterializeProductResponse returns the stored materialization snapshot.
type MaterializeProductResponse struct {
	Materialization ProductMaterialization `json:"materialization"`
}

// AdapterGenerateInstallationContext describes the product/component installation being generated by an integration.
type AdapterGenerateInstallationContext struct {
	Product   ManifestReference `json:"product"`
	Component string            `json:"component"`
	Category  string            `json:"category,omitempty"`
	Class     string            `json:"class,omitempty"`
}

// AdapterGenerateInstallationIntegrationContext gives one external adapter the resolved integration manifests it needs.
type AdapterGenerateInstallationIntegrationContext struct {
	Type         ManifestReference               `json:"type"`
	TypeSpec     IntegrationTypeManifestSpec     `json:"type_spec"`
	Instance     ManifestReference               `json:"instance"`
	InstanceSpec IntegrationInstanceManifestSpec `json:"instance_spec"`
}

// AdapterGenerateInstallationRequest is sent to an integration execute queue to generate one installation-backed product component.
type AdapterGenerateInstallationRequest struct {
	Operation   string                                        `json:"operation"`
	Context     AdapterGenerateInstallationContext            `json:"context"`
	Integration AdapterGenerateInstallationIntegrationContext `json:"integration"`
	Capability  string                                        `json:"capability,omitempty"`
	Input       map[string]any                                `json:"input,omitempty"`
}

// AdapterGenerateInstallationResponse is returned by an integration after generating raw Kubernetes objects.
type AdapterGenerateInstallationResponse struct {
	Operation string           `json:"operation,omitempty"`
	Objects   []map[string]any `json:"objects"`
	Metadata  map[string]any   `json:"metadata,omitempty"`
}

// Backward-compatible aliases retained while the installation vocabulary is rolled out.
type AdapterGenerateProductContext = AdapterGenerateInstallationContext
type AdapterGenerateProductIntegrationContext = AdapterGenerateInstallationIntegrationContext
type AdapterGenerateProductRequest = AdapterGenerateInstallationRequest
type AdapterGenerateProductResponse = AdapterGenerateInstallationResponse
