version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable: []

linters-settings:
  errcheck:
    disable-default-exclusions: false
    exclude-functions:
      - "(*database/sql.Rows).Close"
      - "(*database/sql.Tx).Rollback"
      - "(*database/sql.DB).Close"
      - "(io.Closer).Close"
