apiVersion: v1
kind: PersistentVolume
metadata:
  name: <MS-NAME>-database
  namespace: postgres
  labels:
    app: <MS-NAME>-database
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <MS-NAME>db-claim
  namespace: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi