apiVersion: v1
kind: Service
metadata:
  name: <MS-NAME>-database
  namespace: postgres
  labels:
    app: <MS-NAME>-database
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: <MS-NAME>-database