package httpapi

import (
	_ "embed"
	"net/http"
)

//go:embed openapi.json
var openapiBundle []byte

// handleOpenAPI serves the bundled OpenAPI 3 spec at GET /openapi.json.
//
// The spec is generated by hand and committed at docs/api-reference/openapi.json;
// this file embeds a copy via a build-time symlink (see openapi.json next to this file).
// External tools (Postman, Swagger UI, codegen) can fetch and discover the API contract
// without authentication.
func (s *Server) handleOpenAPI(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=300")
	_, _ = w.Write(openapiBundle)
}
